export const copy = {
  modeExplain: 'Explain',
  modeBuild: 'Build',
  explainPlaceholder: '*/15 9-17 * * 1-5   ·   0 0 12 * * ?   ·   @daily',
  dialectAuto: 'auto',
  dialectStandard: 'standard (5)',
  dialectQuartz: 'Quartz (6)',
  nextHeading: 'Next runs',
  noRuns: 'No run in the next 5 years — this expression never matches.',
  copyButton: 'copy',
  copied: 'copied',
  explainThis: 'explain this',
  sentence: {
    lead: 'Run',
    every: 'every',
    at: 'at',
    onDays: 'on',
    ofMonth: 'of',
    inMonths: 'in',
  },
  fields: {
    interval: 'interval',
    minute: 'minute',
    hours: 'hours',
    dom: 'day of month',
    month: 'month',
    weekday: 'weekday',
    second: 'second',
  },
  note: 'parsed and scheduled on your machine, nothing sent anywhere',
};
